"use strict";
//The game object
//contains info on game state and is a place to store
var game = {
    boardSeq: [],
    userSeq: [],
    UserTurn: false,
    level: 0,

    //have document.ready activate this on click
    //start a new game @ level 1, score 0, and empty sequence arrays
    newGame: function() {
        this.boardSeq = [];
        this.userSeq = [];
        this.level = 0;
        this.userTurn = false;
        this.levelUp();
    },

    //tell game what to do based on the current level
    levelUp: function() {
        //advance level display
        this.level+=1;
        $("#level").text(this.level);
        //add a tile to sequence and
        this.boardSeq.push(this.randomNo());
        this.userSeq = this.boardSeq.slice(0);
        //play sequence user needs to repeat
        this.playSequence(this.boardSeq);
    },

    //play the sequence generated by createBoardSequence
    playSequence: function(boardSeq) {
        var i = 0;
        var that = this;
        var interval = setInterval(function() {
            that.playSound(boardSeq[i]);
            that.lightTile(boardSeq[i]);
            i++;
            if (i >= boardSeq.length) {
                clearInterval(interval);
                that.activateBoard();
            }
        }, 600);
    },
    //onclick = "recordClick('red')"
    //this function fires after the sequence is played for the user
    //it makes the board clickable to the player
    boardCheck: function(a) {

        this.userTurn;
        //
        var correct = this.userSeq.shift();
        //record a click from the player
        var playerClick = $(a.target).data("tile");
        this.userTurn = (correct === playerClick);
        if (this.userSeq.length === 0 && this.userTurn) {
            this.deactivateBoard();
            this.levelUp();
        //if user clicked wrong tile
        } else if (!this.userTurn) {
            this.deactivateBoard();
            this.endGame();
        }
    },

    //deactivate board and set level back to 0
    endGame: function() {
        this.deactivateBoard();
        $("level").text('0');
    },

    // light tile by looking up data # add and remove lit class
    lightTile: function(tile) {
        var $tile = $("[data-tile=" + tile + "]").addClass('lit');
        window.setTimeout(function() {
            $tile.removeClass('lit');
        }, 400);
    },

    //method to play a sound on cue with lightTile
    playSound: function(sound) {
        var g = new Audio("https://s3.amazonaws.com/freecodecamp/simonSound1.mp3");
        var r = new Audio("https://s3.amazonaws.com/freecodecamp/simonSound2.mp3");
        var b = new Audio("https://s3.amazonaws.com/freecodecamp/simonSound4.mp3");
        var y = new Audio("https://s3.amazonaws.com/freecodecamp/simonSound3.mp3");
        var soundArr = [g, r, b, y];
        soundArr[sound].play();
    },

    activateBoard: function() {
        var that = this;
        $('.board')
            .on('click', '[data-tile]', function(a) {
                that.boardCheck(a);
            })
            .on('mousedown', '[data-tile]', function() {
                $(this).addClass('lit');
                that.playSound($(this).data('tile'))
            })
            .on('mouseup', '[data-tile]', function() {
                $(this).removeClass('lit');
            })

            $('[data-tile]').addClass('hoverable');
    },

    deactivateBoard: function() {
        $('.simon')
            .off('click', '[data-tile]')
            .off('mousedown', '[data-tile]')
            .off('mouseup', '[data-tile]');

        $('[data-tile]').removeClass('hoverable');
    },

    //function to add random number between 0-3 to sequence. Needs to push a new value to array at beginning of level
    randomNo: function() {
        return Math.floor((Math.random() * 4));
    }

}

$(document).ready(function() {
    $("#start").click(function() {
        game.newGame();
    });
});
